/**
 * @file    pin_config.h
 * @brief   Centralized pin configuration for the robot arm
 * 
 * Map CubeMX pin definitions to logical device functions.
 * Update this file when CubeMX GPIO configuration changes.
 */

#ifndef PIN_CONFIG_H
#define PIN_CONFIG_H

#include "main.h"  // From CubeMX

// Define all pins used in the project
#define PIN_LIST \
    X(DRIVER1_STEP, DRIVER1_STEP_GPIO_Port, DRIVER1_STEP_Pin, "DRIVER1_STEP") \
    X(DRIVER1_DIR,  DRIVER1_DIR_GPIO_Port,  DRIVER1_DIR_Pin,  "DRIVER1_DIR")  \
    X(DRIVER1_EN,   DRIVER1_EN_GPIO_Port,   DRIVER1_EN_Pin,   "DRIVER1_EN")   \
    X(DRIVER1_UART, DRIVER1_UART_GPIO_Port, DRIVER1_UART_Pin, "DRIVER1_UART") \
    X(DRIVER2_STEP, DRIVER2_STEP_GPIO_Port, DRIVER2_STEP_Pin, "DRIVER2_STEP") \
    X(DRIVER2_DIR,  DRIVER2_DIR_GPIO_Port,  DRIVER2_DIR_Pin,  "DRIVER2_DIR")  \
    X(DRIVER2_EN,   DRIVER2_EN_GPIO_Port,   DRIVER2_EN_Pin,   "DRIVER2_EN")   \
    X(DRIVER2_UART, DRIVER2_UART_GPIO_Port, DRIVER2_UART_Pin, "DRIVER2_UART") \
    X(DRIVER3_STEP, DRIVER3_STEP_GPIO_Port, DRIVER3_STEP_Pin, "DRIVER3_STEP") \
    X(DRIVER3_DIR,  DRIVER3_DIR_GPIO_Port,  DRIVER3_DIR_Pin,  "DRIVER3_DIR")  \
    X(DRIVER3_EN,   DRIVER3_EN_GPIO_Port,   DRIVER3_EN_Pin,   "DRIVER3_EN")   \
    X(DRIVER3_UART, DRIVER3_UART_GPIO_Port, DRIVER3_UART_Pin, "DRIVER3_UART") \
    X(DRIVER4_STEP, DRIVER4_STEP_GPIO_Port, DRIVER4_STEP_Pin, "DRIVER4_STEP") \
    X(DRIVER4_DIR,  DRIVER4_DIR_GPIO_Port,  DRIVER4_DIR_Pin,  "DRIVER4_DIR")  \
    X(DRIVER4_EN,   DRIVER4_EN_GPIO_Port,   DRIVER4_EN_Pin,   "DRIVER4_EN")   \
    X(DRIVER4_UART, DRIVER4_UART_GPIO_Port, DRIVER4_UART_Pin, "DRIVER4_UART") \
    X(DRIVER5_STEP, DRIVER5_STEP_GPIO_Port, DRIVER5_STEP_Pin, "DRIVER5_STEP") \
    X(DRIVER5_DIR,  DRIVER5_DIR_GPIO_Port,  DRIVER5_DIR_Pin,  "DRIVER5_DIR")  \
    X(DRIVER5_EN,   DRIVER5_EN_GPIO_Port,   DRIVER5_EN_Pin,   "DRIVER5_EN")   \
    X(DRIVER5_UART, DRIVER5_UART_GPIO_Port, DRIVER5_UART_Pin, "DRIVER5_UART") \
    X(DRIVER6_STEP, DRIVER6_STEP_GPIO_Port, DRIVER6_STEP_Pin, "DRIVER6_STEP") \
    X(DRIVER6_DIR,  DRIVER6_DIR_GPIO_Port,  DRIVER6_DIR_Pin,  "DRIVER6_DIR")  \
    X(DRIVER6_EN,   DRIVER6_EN_GPIO_Port,   DRIVER6_EN_Pin,   "DRIVER6_EN")   \
    X(DRIVER6_UART, DRIVER6_UART_GPIO_Port, DRIVER6_UART_Pin, "DRIVER6_UART")
    // DRIVER0_STEP, DRIVER0_DIR, DRIVER0_EN, DRIVER0_UART are defined but not used in this project \
    // X(DRIVER0_STEP, DRIVER0_STEP_GPIO_Port, DRIVER0_STEP_Pin, "DRIVER0_STEP") \
    // X(DRIVER0_DIR,  DRIVER0_DIR_GPIO_Port,  DRIVER0_DIR_Pin,  "DRIVER0_DIR")  \
    // X(DRIVER0_EN,   DRIVER0_EN_GPIO_Port,   DRIVER0_EN_Pin,   "DRIVER0_EN")   \
    // X(DRIVER0_UART, DRIVER0_UART_GPIO_Port, DRIVER0_UART_Pin, "DRIVER0_UART") \
    // DRIVER7_STEP, DRIVER7_DIR, DRIVER7_EN, DRIVER7_UART are defined but not used in this project (PA14 is SWCLK for debugging) \
    // X(DRIVER7_STEP, DRIVER7_STEP_GPIO_Port, DRIVER7_STEP_Pin, "DRIVER7_STEP") \
    // X(DRIVER7_DIR,  DRIVER7_DIR_GPIO_Port,  DRIVER7_DIR_Pin,  "DRIVER7_DIR")  \
    // X(DRIVER7_EN,   DRIVER7_EN_GPIO_Port,   DRIVER7_EN_Pin,   "DRIVER7_EN")   \
    // X(DRIVER7_UART, DRIVER7_UART_GPIO_Port, DRIVER7_UART_Pin, "DRIVER7_UART")

#endif /* PIN_CONFIG_H */